# Reload ~/.tmux.conf with keybinding (Prefix-r)
unbind r
bind r source-file ~/.tmux.conf

# Set prefix as Ctrl-s as global config
#set -g prefix C-b

# Enable mouse manipulate tmux
set -g mouse on

# Set vim motion key as navigation key b/w panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
